<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>d0b96512-3681-4a51-a0e2-0f9c00219a37</groupId>
		<artifactId>poc-parent-pom</artifactId>
		<version>0.0.1-SNAPSHOT</version>
	</parent>
	<groupId>43741aa3-8578-46e7-ba11-bec80c101db9</groupId>
	<artifactId>poc-prototype-api</artifactId>
	<version>1.0.0</version>
	<packaging>mule-application</packaging>

	<name>poc-prototype-api</name>
	<properties>
		<api.groupId>43741aa3-8578-46e7-ba11-bec80c101db9</api.groupId>
		<api.artifactId>singapore-flights-api</api.artifactId>
		<api.version>1.0.0</api.version>
		<api.layer>${api.layer.sapi}</api.layer>
	</properties>
	<build>
		<plugins>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>mule-maven-plugin</artifactId>
				<version>${mule.maven.plugin.version}</version>
				<configuration>
					<sharedLibraries>
						<sharedLibrary>
							<groupId>mysql</groupId>
							<artifactId>mysql-connector-java</artifactId>
						</sharedLibrary>
					</sharedLibraries>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.mulesoft.munit.tools</groupId>
				<artifactId>munit-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>${api.groupId}</groupId>
			<artifactId>${api.artifactId}</artifactId>
			<version>${api.version}</version>
			<classifier>raml</classifier>
			<type>zip</type>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-http-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.modules</groupId>
			<artifactId>mule-apikit-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>org.mule.connectors</groupId>
			<artifactId>mule-db-connector</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>com.mulesoft.modules</groupId>
			<artifactId>mule-secure-configuration-property-module</artifactId>
			<classifier>mule-plugin</classifier>
		</dependency>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.48</version>
		</dependency>
	</dependencies>
</project>
